feat: add previewer
react-component/image pull request #55
Opened 2020-12-24 06:21 UTC by shaodahong

fixes https://github.com/ant-design/ant-design/issues/28321

2020-12-24 06:45 UTC, afc163 commented on examples/previewer.tsx
> +        Image.previewer(
方法调用不是好的范式，要解决的问题是 `需要预览的内容和预览前的内容是不同的`。

2020-12-24 06:46 UTC, afc163 requested changes
方法调用不是好的范式，要解决的问题是 需要预览的内容和预览前的内容是不同的，而不是需要主动触发预览功能。

2020-12-24 07:44 UTC, shaodahong commented
> 方法调用不是好的范式，要解决的问题是 `需要预览的内容和预览前的内容是不同的`，而不是需要主动触发预览功能。

嗯，这个 PR 解决的核心的问题不是 **需要预览的内容和预览前的内容是不同的**，主动预览在不需要 `img` 占位的情况下，介质会变多，比如可以通过 `a` 标签触发，`button` 触发

2020-12-24 08:56 UTC, afc163 commented
```
  <Image.PreviewGroup trigger={<Button>open preview</Button>}>
    <Image src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" />
    <Image src="https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*P0S-QIRUbsUAAAAAAAAAAABkARQnAQ" />
  </Image.PreviewGroup>
```

这样如何，有 trigger 就隐藏 image。

2020-12-24 09:06 UTC, shaodahong commented
> ```
>   <Image.PreviewGroup trigger={<Button>open preview</Button>}>
>     <Image src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" />
>     <Image src="https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*P0S-QIRUbsUAAAAAAAAAAABkARQnAQ" />
>   </Image.PreviewGroup>
> ```
> 
> 这样如何，有 trigger 就隐藏 image。

一般般，举个例子，比如 `Upload` 组件

![image](https://user-images.githubusercontent.com/14831261/103076989-e4128100-4609-11eb-9750-466897da4ff9.png)

现在默认是新标签打开，如果我想在 `onPreview` 里面用一个预览模式打开最方便的应该是

```jsx
onPreview = file => Image.previewer(file.url)
```

如果用 `Modal` 打开就是

```jsx
onPreview = file => Modal.Confirm({ content: <img src={file.url} />, footer: null })
```

2020-12-24 09:11 UTC, afc163 commented
```
  <Image.PreviewGroup previewVisible={this.state.previewVisible} showChildren={false} onPreviewVisibleChange={}>
    <Image src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png" />
    <Image src="https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*P0S-QIRUbsUAAAAAAAAAAABkARQnAQ" />
  </Image.PreviewGroup>
```

那最好是做成受控模式，静态方法调用对于 Context 场景（redux/国际化/prefixCls）都有很多问题，不建议使用。

2020-12-25 05:17 UTC, zombieJ commented
我也不赞成做成静态方法，看起来的确是 Group 的受控场景。

2020-12-25 05:18 UTC, zombieJ commented
`showChildren` 感觉也没有必要。这个 issue 里的场景看，其实应该受控后自己样式隐藏掉 div 即可。

2020-12-28 09:33 UTC, afc163 commented
应该和 https://github.com/ant-design/ant-design/issues/27273 这个需求更类似。

2020-12-31 08:31 UTC, closed without merging

2021-02-02 10:10 UTC, GitKou commented on examples/previewer.tsx
> +        Image.previewer(
有些场景去要通过点击“预览”按钮触发预览